CREATE TABLE IF NOT EXISTS public.gs_game_info (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name TEXT PRIMARY KEY,
  title TEXT,
  content TEXT,
  detail TEXT,
  iframe_url TEXT,
  original_url TEXT,
  image_url TEXT,
  thumbnail_url TEXT,
  website_data TEXT,
  collection_time TIMESTAMPTZ,
  star_rating INTEGER,
  tag_name TEXT,
  category_name TEXT,
  create_time timestamp with time zone not null default now()
) TABLESPACE pg_default;

create table if not exists public.gs_game_category (
    id bigint primary key generated always as identity,
    name text not null,
    title text,
    image_url TEXT,
    sort integer,
    del_flag integer default 0, -- 默认值可以设为0，但COMMENT要单独写
    create_by bigint default 0, -- 默认值可以设为0，但COMMENT要单独写
    create_time timestamp with time zone not null default now()
  ) TABLESPACE pg_default;